### ISSUE TITLE
Error in intialize Parameter

### ISSUE THREAD

**Issue by henrifnk** [henrifnk/mlr3learners.rweka#1]
`Weka_control` contains parameter-ids that trigger the following Errormessage, when creating `LearnerClassifJRip$new()`,  :

>  Error in assert_id(id) : 
  Assertion on 'id' failed: Must comply to pattern '^[[:alpha:]]+[[:alnum:]_.]*$'.

For that reason, I skipped adding the concerning Parameters to the ParamSet so far...

___

The concerning Parameters:
`output-debug-info`
        If set, classifier is run in debug mode and may output additional info to the
        console
`do-not-check-capabilities`
        If set, classifier capabilities are not checked before classifier is built (use
        with caution).
`num-decimal-places`
        The number of decimal places for the output of numbers in the model (default
        2).
	Number of arguments: 1.
`batch-size`
        The desired batch size for batch prediction (default 100).
	Number of arguments: 1.

___

A related Error occured in mlr already
https://github.com/mlr-org/ParamHelpers/issues/166

**Comment by pat-s** [comment]
You can set [custom defaults](https://github.com/mlr-org/mlr3learners/blob/0e3a1093ef6285726edd67f4540f77cc85ba87c8/R/LearnerRegrXgboost.R#L92-L93) if the actual defaults are causing issues (but only if there is good reasoning for it). Changed defaults need to be documented.

**Comment by henrifnk** [comment]
@pat-s
The problem is not the default but the id itself.
Unfortunately they contain "-", what makes them illegal assign objects to R.
The weird spelling occurs because R is passing those values to Java by `rJava`...
However I integrated the ids by replacing "-" by "_"...
Still I couldn't find a way to apply `output-debug-info` and `do-not-check-capabilities` since I don't know how to pass logicals regularly to rJava...
Any idea?

**Comment by henrifnk** [comment]
Solved the issue myself see `R\LearnerClassifJRip.R` for implementation details

**Comment by pat-s** [comment]
👍 Should work.

PS: Try to avoid "I" statements in the DESC: Just use passive voice, i.e. 

> #' The ids of the following control-agruments (typo!) were changed because they did not follow a valid R pattern for object names:
