### ISSUE TITLE
Learner review

### ISSUE THREAD

**Issue by pat-s** [henrifnk/mlr3learners.rweka#3]
Thanks!

- [x] Apply mlr-style (also to /inst) files

- [x] prefix `invoke` with `mlr3misc::`

- [x] replace `do.call()` with `mlr3misc::invoke()`

- [x] Check spelling: https://github.com/henrifnk/mlr3learners.rweka/blob/587667e55cfccd7f2c1a9680ac31b5187ccd40d8/R/LearnerClassifJRip.R#L9

- [x] replace `<-`  with `=`

> for paramtest on linux openjdk-8-jdk was neccesary... for more infos see commit

All of this should not be needed, the default JDK works - `sudo R CMD javareconf` should be enough.

**Comment by henrifnk** [comment]
Hope I fixed all issues
Once I have your confirmation I'll transfer it to `mlr3learners`

**Comment by pat-s** [comment]
Thanks, looks good! Good work @henrifnk. 

You can transfer the repo and try to init the mlr3learners.drat deployment yourself. LMK if you face any issues.
